services:
  orion:
    image: telefonicaiot/fiware-orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbURI mongodb://mongo
    networks:
      - fiware

  mongo:
    image: mongo:8.0
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fiware

  weather-alert-course:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        - APP_FILE=weather_alert_course
        - CONFIG=server
    environment:
      - PYTHONUNBUFFERED=1
      - ORION_URL=http://orion:1026
      - CALLBACK_URL=http://weather-alert-course:5000/notify
    depends_on:
      - orion
    networks:
      - fiware

  weather-context-enricher:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        - APP_FILE=weather_context_enricher
        - CONFIG=server
    environment:
      - PYTHONUNBUFFERED=1
      - ORION_URL=http://orion:1026
      - CALLBACK_URL=http://weather-context-enricher:5000/notify
    depends_on:
      - orion
    networks:
      - fiware

  weather-simulator:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        - APP_FILE=weather_simulator
        - CONFIG=script
    environment:
      - PYTHONUNBUFFERED=1
      - ORION_URL=http://orion:1026
    depends_on:
      - orion
    networks:
      - fiware

  course-instance-simulator:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        - APP_FILE=course_instance_simulator
        - CONFIG=script
    environment:
      - PYTHONUNBUFFERED=1
      - ORION_URL=http://orion:1026
      - ENTITIES_DIR=./entities
    depends_on:
      - orion
    networks:
      - fiware
    volumes:
      - ./entities:/app/entities:ro

networks:
  fiware:
